### PR TITLE
Newsweek homepage

### PR DESCRIPTION
**Pull request by martinnajjar12**
### Newsweek homepage
We've cloned the homepage of Newsweek website using these technologies:

- HTML5
- CSS3
- Bootstrap

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

 WOW, what project! ⭐


#### Hey @jonathastavares and @martinnajjar12, Is a pleasure to review such a good project! Congrats for the amazing work you guys already did, the project looks awesome! It breaks my heart 💔 not approve it right away, but I swear, we're almost done, there are just some minor changes that you guys have to implement to proceed:

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵

- [x] Improve the fixed navbar in all screens (small, medium, and large)
- [x] Remove that white rectangle
image

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [x] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
image
Your HTML will be something like this: 
image
Apply the same logic above in **ALL** those repeated rules listed below:
```
       9 |   font-weight: bold;
       5 |   margin: 0;
```

## [OPTIONAL CHANGES]
- [x] Add a favicon to make it more similar to the original page;

## Summary (AWESOMENESS ⭐)
✨ Team, I know a great project when I see one. And wow! Thats one of the best newsweek projects I've ever reviewed!
✨ Nice usage of bootstrap!
✨ Your page looks AWESOME! 👏
✨ Awesome CSS practices, congrats 😎
✨ Again, good job with that project, it looks almost perfect💥
✨ Very organized repo 🗃
✨ Perfect usage of semantic HTML with `<article>` ,` <section>` tags 🥇
✨ You guys got my attention, I'll keep my eyes on you! Keep up the good work! 🐱‍👓

## Please make the required changes and resubmit for a new code review once you are ready💪
That was close

## As always, I wish you all the very best and see you both at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Comment by martinnajjar12** [comment]
> # [STATUS] CHANGES REQUIRED♻️
> WOW, what project! ⭐
> 
> 
> #### Hey @jonathastavares and @martinnajjar12, Is a pleasure to review such a good project! Congrats for the amazing work you guys already did, the project looks awesome! It breaks my heart 💔 not approve it right away, but I swear, we're almost done, there are just some minor changes that you guys have to implement to proceed:
> _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
> 
> ## [REQUIRED CHANGES]
> #### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
> * [x]  Improve the fixed navbar in all screens (small, medium, and large)
> * [x]  Remove that white rectangle
>   image
> 
> #### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
> * [x]  Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
>   Take a look at this example:
>   image
>   Your HTML will be something like this:
>   image
>   Apply the same logic above in **ALL** those repeated rules listed below:
> 
> ```
>        9 |   font-weight: bold;
>        5 |   margin: 0;
> ```
> 
> ## [OPTIONAL CHANGES]
> * [x]  Add a favicon to make it more similar to the original page;
> 
> ## Summary (AWESOMENESS ⭐)
> ✨ Team, I know a great project when I see one. And wow! Thats one of the best newsweek projects I've ever reviewed!
> ✨ Nice usage of bootstrap!
> ✨ Your page looks AWESOME! 👏
> ✨ Awesome CSS practices, congrats 😎
> ✨ Again, good job with that project, it looks almost perfect💥
> ✨ Very organized repo 🗃
> ✨ Perfect usage of semantic HTML with `<article>` ,` <section>` tags 🥇
> ✨ You guys got my attention, I'll keep my eyes on you! Keep up the good work! 🐱‍👓
> 
> ## Please make the required changes and resubmit for a new code review once you are ready💪
> That was close
> 
> 
> ## As always, I wish you all the very best and see you both at the top🚀
> 👨🏻‍💻 **TSE: Kevin Alves**
> 
> 📫 Have any question? Better call Kevin:
> 
> [ gmail](mailto:kevinalves.js@gmail.com) [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)
> 
> *We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.

**I don't know how to thank you, because your words are so polite and motivational. You're an AMAZING person.**

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

### Hello @martinnajjar12 and @jonathastavares :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by martinnajjar12** [comment]
> # Status: Approved 🟢
> ### Hello @martinnajjar12 and @jonathastavares 👋
> ### Thank you for making all of the required changes, your project is approved 👏 👏 👏
> ### You may merge, good luck with your next projects 🚀
> Murilo Roque Paiva da Silva
> 
> * Github: [@muriloroque](https://github.com/MuriloRoque)
> * Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)
> 
> [Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Thank you so much**

**Pull request merged**
